// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjbmigqhdfaxaudiupht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYm1pZ3FoZGZheGF1ZGl1cGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNzA5MzEsImV4cCI6MjA5MDY0NjkzMX0.SlAcqvsNQHHHlMoR0CPORkLkHsPbPOXB_818Bu_O104";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});